version: '3.9'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dbTec 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
      
    ports:
    - 3306:3306
    command: --init-file /docker-entrypoint-initdb.d/dbTec.sql
    networks:
      - appdb    
    volumes:
      - ./dbTec.sql:/docker-entrypoint-initdb.d/dbTec.sql
      - db_data:/var/lib/mysql

  backend:
    image: camran1234/donformulario-backend:latest
    restart: on-failure
    networks:
      - appdb
    ports:
      - 4000:4000
    depends_on:
      - db

  frontend:
    image: camran1234/donformulario-frontend:latest
    restart: on-failure
    networks:
      - appdb
    ports:
      - 80:80
    depends_on:
      - backend
    
  

volumes:
  db_data:

networks:
  appdb:
    driver: bridge