version: '3.9'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dbTec 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
      
    ports:
    - 3306:3306
    command: --init-file /docker-entrypoint-initdb.d/dbTec.sql
    networks:
      - appdb    
    volumes:
      - ./dbTec.sql:/docker-entrypoint-initdb.d/dbTec.sql
      - db_data:/var/lib/mysql

  backend:
    build: ./ptec-backend
    restart: on-failure
    networks:
      - appdb
    ports:
      - 4000:4000
    depends_on:
      - db

  frontend:
    build: ./ptec-frontend
    restart: on-failure
    networks:
      - appdb
    ports:
      - 3000:3000
    depends_on:
      - backend
    
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - frontend

volumes:
  db_data:

networks:
  appdb:
    driver: bridge