version: '3.9'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dbTec 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
      
    ports:
    - 3306:3306
    command: --init-file /docker-entrypoint-initdb.d/dbTec.sql
    networks:
      - appdb    
    volumes:
      - ./dbTec.sql:/docker-entrypoint-initdb.d/dbTec.sql
      - db_data:/var/lib/mysql

  backend:
    build: ./ptec_backend
    restart: on-failure
    networks:
      - appdb
    ports:
      - 4000:4000
    depends_on:
      - db

  frontend:
    build: ./ptec_frontend
    volumes:
      - frontend:/var/lib/frontend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always

volumes:
  db_data:
  frontend:

networks:
  appdb:
    driver: bridge